development:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/lojadopintor_development.sqlite3
  pool: 5

test:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/lojadopintor_test.sqlite3
  pool: 5

production:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/lojadopintor_production.sqlite3
  pool: 5

# test:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: lojadopintor_test
#   pool: 5
#   username: root
#   password:
#   socket: /var/run/mysqld/mysqld.sock

# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: lojadopintor_development
#   pool: 5
#   username: root
#   password:
#   socket: /var/run/mysqld/mysqld.sock