development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: lojadopintor_development
  pool: 5
  username: root
  password: budal33
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: lojadopintor_test
  pool: 5
  username: root
  password: budal33
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: lojadopintor_production
  pool: 5
  username: root
  password: budal33
  socket: /var/run/mysqld/mysqld.sock